In [1]:
import tensorflow
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
# sentance 
sent=[ 'the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good',
]

In [3]:
# define the vocabulary size
voc_size =10000

In [4]:
# one hot encoding 
one_hot_repr = [one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8827, 8288, 3430, 2063],
 [8827, 8288, 3430, 1929],
 [8827, 1223, 3430, 9429],
 [3637, 8838, 8248, 9811, 8098],
 [3637, 8838, 8248, 9811, 400],
 [5677, 8827, 2543, 3430, 6208],
 [9565, 328, 917, 9811]]

In [5]:
# word embading rep

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np

In [7]:
sent_length=8
embedded_docs  =pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)

In [8]:
embedded_docs

array([[   0,    0,    0,    0, 8827, 8288, 3430, 2063],
       [   0,    0,    0,    0, 8827, 8288, 3430, 1929],
       [   0,    0,    0,    0, 8827, 1223, 3430, 9429],
       [   0,    0,    0, 3637, 8838, 8248, 9811, 8098],
       [   0,    0,    0, 3637, 8838, 8248, 9811,  400],
       [   0,    0,    0, 5677, 8827, 2543, 3430, 6208],
       [   0,    0,    0,    0, 9565,  328,  917, 9811]])

In [9]:
# feature representation 
dim =10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 352ms/step


array([[[ 0.00180154,  0.04774228, -0.00566608,  0.045038  ,
          0.00842093, -0.03798749, -0.03154745,  0.01837939,
          0.03149194, -0.04612872],
        [ 0.00180154,  0.04774228, -0.00566608,  0.045038  ,
          0.00842093, -0.03798749, -0.03154745,  0.01837939,
          0.03149194, -0.04612872],
        [ 0.00180154,  0.04774228, -0.00566608,  0.045038  ,
          0.00842093, -0.03798749, -0.03154745,  0.01837939,
          0.03149194, -0.04612872],
        [ 0.00180154,  0.04774228, -0.00566608,  0.045038  ,
          0.00842093, -0.03798749, -0.03154745,  0.01837939,
          0.03149194, -0.04612872],
        [ 0.04739647, -0.03494911, -0.03931747,  0.0184953 ,
          0.04230598, -0.04999664,  0.04080847,  0.01132456,
          0.02293627,  0.00327814],
        [ 0.03005247,  0.03195437,  0.01281345, -0.00371663,
         -0.03145303,  0.02298773,  0.03027706, -0.049833  ,
         -0.0288923 ,  0.04720564],
        [-0.02936916,  0.03961655,  0.00302856, -0.0

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 8827, 8288, 3430, 2063])

In [14]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 115ms/step


array([[ 0.00180154,  0.04774228, -0.00566608,  0.045038  ,  0.00842093,
        -0.03798749, -0.03154745,  0.01837939,  0.03149194, -0.04612872],
       [ 0.00180154,  0.04774228, -0.00566608,  0.045038  ,  0.00842093,
        -0.03798749, -0.03154745,  0.01837939,  0.03149194, -0.04612872],
       [ 0.00180154,  0.04774228, -0.00566608,  0.045038  ,  0.00842093,
        -0.03798749, -0.03154745,  0.01837939,  0.03149194, -0.04612872],
       [ 0.00180154,  0.04774228, -0.00566608,  0.045038  ,  0.00842093,
        -0.03798749, -0.03154745,  0.01837939,  0.03149194, -0.04612872],
       [ 0.04739647, -0.03494911, -0.03931747,  0.0184953 ,  0.04230598,
        -0.04999664,  0.04080847,  0.01132456,  0.02293627,  0.00327814],
       [ 0.03005247,  0.03195437,  0.01281345, -0.00371663, -0.03145303,
         0.02298773,  0.03027706, -0.049833  , -0.0288923 ,  0.04720564],
       [-0.02936916,  0.03961655,  0.00302856, -0.00661838,  0.01433158,
         0.01686153,  0.02135913, -0.01909256